RegisterNetEvent('LamaLottery:showNotification')
AddEventHandler('LamaLottery:showNotification', function(message)
    SetNotificationTextEntry('STRING') 
	AddTextComponentString(message)
	DrawNotification(0,1)
end)